const { clothingImage } = require('./cloudAssets.js')
const categories = [
  { id: 'all', name: '精选' },
  { id: 'qipao', name: '旗袍' },
  { id: 'tongzhuang', name: '童装' },
  { id: 'hanfu', name: '汉服' }
]

const banners = [
  {
    id: 1,
    title: '墨绿提花旗袍',
    subtitle: '旗袍精选',
    desc: '墨绿色缎面提花面料，立领盘扣，手持折扇，古典雅致...',
    image: clothingImage(8),
    color: '#8B4513'
  },
  {
    id: 2,
    title: '黑色亮面旗袍',
    subtitle: '旗袍精选',
    desc: '黑色亮面面料，金色纹路，复古奢华，留声机背景...',
    image: clothingImage(25),
    color: '#8B4513'
  },
  {
    id: 3,
    title: '新中式马面裙套装',
    subtitle: '汉服精选',
    desc: '白色刺绣上衣配黑色印花马面裙，古典优雅...',
    image: clothingImage(7),
    color: '#8B4513'
  },
]

const clothingList = [
  {
    id: 1,
    name: '儿童米色西装六件套',
    category: 'tongzhuang',
    categoryName: '男童',
    subtitle: '花童礼服，米色西装套装，含西装外套、马甲...',
    desc: '花童礼服，米色西装套装，含西装外套、马甲、衬衫、长裤、领结、胸花',
    detailDesc: '款式：儿童米色西装六件套\n类别：男童\n描述：花童礼服，米色西装套装，含西装外套、马甲、衬衫、长裤、领结、胸花\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(1),
    images: [clothingImage(1)],
    price: '¥236',
    tags: ['童装', '可爱', '精致'],
    liked: false
  },
  {
    id: 2,
    name: '儿童黑白背带四件套',
    category: 'tongzhuang',
    categoryName: '男童',
    subtitle: '经典黑白配色，含衬衫、短裤、领结、背带，...',
    desc: '经典黑白配色，含衬衫、短裤、领结、背带，帅气有型',
    detailDesc: '款式：儿童黑白背带四件套\n类别：男童\n描述：经典黑白配色，含衬衫、短裤、领结、背带，帅气有型\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(2),
    images: [clothingImage(2)],
    price: '¥273',
    tags: ['童装', '可爱', '精致'],
    liked: false
  },
  {
    id: 3,
    name: '儿童粉色马甲五件套',
    category: 'tongzhuang',
    categoryName: '男童',
    subtitle: '温柔粉色系，含马甲、衬衫、短裤、领结、胸...',
    desc: '温柔粉色系，含马甲、衬衫、短裤、领结、胸花，绅士优雅',
    detailDesc: '款式：儿童粉色马甲五件套\n类别：男童\n描述：温柔粉色系，含马甲、衬衫、短裤、领结、胸花，绅士优雅\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(3),
    images: [clothingImage(3)],
    price: '¥310',
    tags: ['童装', '可爱', '精致'],
    liked: false
  },
  {
    id: 4,
    name: '儿童胡子背带四件套',
    category: 'tongzhuang',
    categoryName: '男童',
    subtitle: '趣味胡子图案背带，黑白经典配色，活泼可爱...',
    desc: '趣味胡子图案背带，黑白经典配色，活泼可爱',
    detailDesc: '款式：儿童胡子背带四件套\n类别：男童\n描述：趣味胡子图案背带，黑白经典配色，活泼可爱\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(4),
    images: [clothingImage(4)],
    price: '¥347',
    tags: ['童装', '可爱', '精致'],
    liked: false
  },
  {
    id: 5,
    name: '儿童米色马甲短裤套装',
    category: 'tongzhuang',
    categoryName: '男童',
    subtitle: '米色马甲配短裤，清新淡雅，适合多种场合...',
    desc: '米色马甲配短裤，清新淡雅，适合多种场合',
    detailDesc: '款式：儿童米色马甲短裤套装\n类别：男童\n描述：米色马甲配短裤，清新淡雅，适合多种场合\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(5),
    images: [clothingImage(5)],
    price: '¥384',
    tags: ['童装', '可爱', '精致'],
    liked: false
  },
  {
    id: 6,
    name: '儿童卡其色西装套装',
    category: 'tongzhuang',
    categoryName: '男童',
    subtitle: '卡其色西装外套配长裤，绅士小礼服风格...',
    desc: '卡其色西装外套配长裤，绅士小礼服风格',
    detailDesc: '款式：儿童卡其色西装套装\n类别：男童\n描述：卡其色西装外套配长裤，绅士小礼服风格\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(6),
    images: [clothingImage(6)],
    price: '¥421',
    tags: ['童装', '可爱', '精致'],
    liked: false
  },
  {
    id: 7,
    name: '新中式马面裙套装',
    category: 'hanfu',
    categoryName: '汉服',
    subtitle: '白色刺绣上衣配黑色印花马面裙，古典优雅...',
    desc: '白色刺绣上衣配黑色印花马面裙，古典优雅',
    detailDesc: '款式：新中式马面裙套装\n类别：汉服\n描述：白色刺绣上衣配黑色印花马面裙，古典优雅\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(7),
    images: [clothingImage(7)],
    price: '¥458',
    tags: ['汉服', '古典', '刺绣'],
    liked: false
  },
  {
    id: 8,
    name: '墨绿提花旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '墨绿色缎面提花面料，立领盘扣，手持折扇，...',
    desc: '墨绿色缎面提花面料，立领盘扣，手持折扇，古典雅致',
    detailDesc: '款式：墨绿提花旗袍\n类别：旗袍\n描述：墨绿色缎面提花面料，立领盘扣，手持折扇，古典雅致\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(8),
    images: [clothingImage(8)],
    price: '¥495',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 9,
    name: '橄榄绿蕾丝旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '橄榄绿色蕾丝面料，修身剪裁，手持团扇，温...',
    desc: '橄榄绿色蕾丝面料，修身剪裁，手持团扇，温婉动人',
    detailDesc: '款式：橄榄绿蕾丝旗袍\n类别：旗袍\n描述：橄榄绿色蕾丝面料，修身剪裁，手持团扇，温婉动人\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(9),
    images: [clothingImage(9)],
    price: '¥532',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 10,
    name: '蓝格纯棉旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '浅蓝色格子纯棉面料，七分袖设计，清新文艺...',
    desc: '浅蓝色格子纯棉面料，七分袖设计，清新文艺',
    detailDesc: '款式：蓝格纯棉旗袍\n类别：旗袍\n描述：浅蓝色格子纯棉面料，七分袖设计，清新文艺\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(10),
    images: [clothingImage(10)],
    price: '¥569',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 11,
    name: '墨绿短袖旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '墨绿色短袖旗袍，手持折扇，园林外景，古典...',
    desc: '墨绿色短袖旗袍，手持折扇，园林外景，古典韵味',
    detailDesc: '款式：墨绿短袖旗袍\n类别：旗袍\n描述：墨绿色短袖旗袍，手持折扇，园林外景，古典韵味\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(11),
    images: [clothingImage(11)],
    price: '¥606',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 12,
    name: '灰色棉麻旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '灰色棉麻面料，白色盘扣装饰，简约素雅...',
    desc: '灰色棉麻面料，白色盘扣装饰，简约素雅',
    detailDesc: '款式：灰色棉麻旗袍\n类别：旗袍\n描述：灰色棉麻面料，白色盘扣装饰，简约素雅\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(12),
    images: [clothingImage(12)],
    price: '¥643',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 13,
    name: '黑金披肩旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '黑色蕾丝旗袍配黑色流苏披肩，金色纹样，华...',
    desc: '黑色蕾丝旗袍配黑色流苏披肩，金色纹样，华丽复古',
    detailDesc: '款式：黑金披肩旗袍\n类别：旗袍\n描述：黑色蕾丝旗袍配黑色流苏披肩，金色纹样，华丽复古\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(13),
    images: [clothingImage(13)],
    price: '¥680',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 14,
    name: '印花圆盘旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '米色底印花圆盘图案旗袍，搭配草帽，法式中...',
    desc: '米色底印花圆盘图案旗袍，搭配草帽，法式中国风',
    detailDesc: '款式：印花圆盘旗袍\n类别：旗袍\n描述：米色底印花圆盘图案旗袍，搭配草帽，法式中国风\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(14),
    images: [clothingImage(14)],
    price: '¥717',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 15,
    name: '条纹素雅旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '白底黑条纹旗袍，手持绿叶，清新自然...',
    desc: '白底黑条纹旗袍，手持绿叶，清新自然',
    detailDesc: '款式：条纹素雅旗袍\n类别：旗袍\n描述：白底黑条纹旗袍，手持绿叶，清新自然\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(15),
    images: [clothingImage(15)],
    price: '¥754',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 16,
    name: '灰色碎花旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '灰色底碎花图案旗袍，无袖设计，端庄大方...',
    desc: '灰色底碎花图案旗袍，无袖设计，端庄大方',
    detailDesc: '款式：灰色碎花旗袍\n类别：旗袍\n描述：灰色底碎花图案旗袍，无袖设计，端庄大方\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(16),
    images: [clothingImage(16)],
    price: '¥791',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 17,
    name: '儿童浅蓝旗袍裙',
    category: 'tongzhuang',
    categoryName: '女童',
    subtitle: '浅蓝色无袖旗袍上衣配白色蕾丝裙摆，手持团...',
    desc: '浅蓝色无袖旗袍上衣配白色蕾丝裙摆，手持团扇，清新甜美',
    detailDesc: '款式：儿童浅蓝旗袍裙\n类别：女童\n描述：浅蓝色无袖旗袍上衣配白色蕾丝裙摆，手持团扇，清新甜美\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(17),
    images: [clothingImage(17)],
    price: '¥828',
    tags: ['童装', '可爱', '精致'],
    liked: false
  },
  {
    id: 18,
    name: '儿童粉色刺绣套装',
    category: 'tongzhuang',
    categoryName: '女童',
    subtitle: '粉色刺绣马甲配白色百褶裙，手持蝴蝶扇，精...',
    desc: '粉色刺绣马甲配白色百褶裙，手持蝴蝶扇，精致可爱',
    detailDesc: '款式：儿童粉色刺绣套装\n类别：女童\n描述：粉色刺绣马甲配白色百褶裙，手持蝴蝶扇，精致可爱\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(18),
    images: [clothingImage(18)],
    price: '¥865',
    tags: ['童装', '可爱', '精致'],
    liked: false
  },
  {
    id: 19,
    name: '儿童粉色蛋糕裙',
    category: 'tongzhuang',
    categoryName: '女童',
    subtitle: '粉色无袖旗袍上衣配白色蛋糕裙摆，手持蝴蝶...',
    desc: '粉色无袖旗袍上衣配白色蛋糕裙摆，手持蝴蝶扇，甜美俏皮',
    detailDesc: '款式：儿童粉色蛋糕裙\n类别：女童\n描述：粉色无袖旗袍上衣配白色蛋糕裙摆，手持蝴蝶扇，甜美俏皮\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(19),
    images: [clothingImage(19)],
    price: '¥902',
    tags: ['童装', '可爱', '精致'],
    liked: false
  },
  {
    id: 20,
    name: '黑色丝绒旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '黑色丝绒面料，白色珍珠装饰领口，手持团扇...',
    desc: '黑色丝绒面料，白色珍珠装饰领口，手持团扇，高贵典雅',
    detailDesc: '款式：黑色丝绒旗袍\n类别：旗袍\n描述：黑色丝绒面料，白色珍珠装饰领口，手持团扇，高贵典雅\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(20),
    images: [clothingImage(20)],
    price: '¥939',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 21,
    name: '紫色丝绒旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '紫色丝绒面料，立领设计，高贵神秘...',
    desc: '紫色丝绒面料，立领设计，高贵神秘',
    detailDesc: '款式：紫色丝绒旗袍\n类别：旗袍\n描述：紫色丝绒面料，立领设计，高贵神秘\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(21),
    images: [clothingImage(21)],
    price: '¥976',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 22,
    name: '粉色刺绣旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '粉色刺绣面料，短款设计，甜美可人...',
    desc: '粉色刺绣面料，短款设计，甜美可人',
    detailDesc: '款式：粉色刺绣旗袍\n类别：旗袍\n描述：粉色刺绣面料，短款设计，甜美可人\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(22),
    images: [clothingImage(22)],
    price: '¥1013',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 23,
    name: '红色蕾丝旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '红色蕾丝面料，修身剪裁，喜庆热烈...',
    desc: '红色蕾丝面料，修身剪裁，喜庆热烈',
    detailDesc: '款式：红色蕾丝旗袍\n类别：旗袍\n描述：红色蕾丝面料，修身剪裁，喜庆热烈\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(23),
    images: [clothingImage(23)],
    price: '¥1050',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 24,
    name: '蓝色真丝旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '蓝色真丝面料，水墨印花，清雅脱俗...',
    desc: '蓝色真丝面料，水墨印花，清雅脱俗',
    detailDesc: '款式：蓝色真丝旗袍\n类别：旗袍\n描述：蓝色真丝面料，水墨印花，清雅脱俗\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(24),
    images: [clothingImage(24)],
    price: '¥1087',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 25,
    name: '黑色亮面旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '黑色亮面面料，金色纹路，复古奢华，留声机...',
    desc: '黑色亮面面料，金色纹路，复古奢华，留声机背景',
    detailDesc: '款式：黑色亮面旗袍\n类别：旗袍\n描述：黑色亮面面料，金色纹路，复古奢华，留声机背景\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(25),
    images: [clothingImage(25)],
    price: '¥1124',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 26,
    name: '白色蕾丝旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '白色蕾丝面料，纯洁优雅，适合多种场合...',
    desc: '白色蕾丝面料，纯洁优雅，适合多种场合',
    detailDesc: '款式：白色蕾丝旗袍\n类别：旗袍\n描述：白色蕾丝面料，纯洁优雅，适合多种场合\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(26),
    images: [clothingImage(26)],
    price: '¥1161',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 27,
    name: '绿色碎花旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '绿色底碎花图案，清新自然，田园风格...',
    desc: '绿色底碎花图案，清新自然，田园风格',
    detailDesc: '款式：绿色碎花旗袍\n类别：旗袍\n描述：绿色底碎花图案，清新自然，田园风格\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(27),
    images: [clothingImage(27)],
    price: '¥1198',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 28,
    name: '黄色真丝旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '黄色真丝面料，金色刺绣，华贵大气...',
    desc: '黄色真丝面料，金色刺绣，华贵大气',
    detailDesc: '款式：黄色真丝旗袍\n类别：旗袍\n描述：黄色真丝面料，金色刺绣，华贵大气\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(28),
    images: [clothingImage(28)],
    price: '¥1235',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 29,
    name: '藏青印花旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '藏青色底印花面料，沉稳大气...',
    desc: '藏青色底印花面料，沉稳大气',
    detailDesc: '款式：藏青印花旗袍\n类别：旗袍\n描述：藏青色底印花面料，沉稳大气\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(29),
    images: [clothingImage(29)],
    price: '¥1272',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 30,
    name: '蓝色刺绣旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '蓝色刺绣面料，手持珍珠包，优雅知性...',
    desc: '蓝色刺绣面料，手持珍珠包，优雅知性',
    detailDesc: '款式：蓝色刺绣旗袍\n类别：旗袍\n描述：蓝色刺绣面料，手持珍珠包，优雅知性\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(30),
    images: [clothingImage(30)],
    price: '¥1309',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 31,
    name: '米色提花旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '米色提花面料，简约大方，日常穿着...',
    desc: '米色提花面料，简约大方，日常穿着',
    detailDesc: '款式：米色提花旗袍\n类别：旗袍\n描述：米色提花面料，简约大方，日常穿着\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(31),
    images: [clothingImage(31)],
    price: '¥1346',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 32,
    name: '粉色碎花旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '粉色碎花面料，甜美浪漫...',
    desc: '粉色碎花面料，甜美浪漫',
    detailDesc: '款式：粉色碎花旗袍\n类别：旗袍\n描述：粉色碎花面料，甜美浪漫\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(32),
    images: [clothingImage(32)],
    price: '¥1383',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 33,
    name: '墨绿丝绒旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '墨绿色丝绒面料，高贵典雅...',
    desc: '墨绿色丝绒面料，高贵典雅',
    detailDesc: '款式：墨绿丝绒旗袍\n类别：旗袍\n描述：墨绿色丝绒面料，高贵典雅\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(33),
    images: [clothingImage(33)],
    price: '¥1420',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 34,
    name: '紫色印花旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '紫色印花面料，浪漫唯美...',
    desc: '紫色印花面料，浪漫唯美',
    detailDesc: '款式：紫色印花旗袍\n类别：旗袍\n描述：紫色印花面料，浪漫唯美\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(34),
    images: [clothingImage(34)],
    price: '¥1457',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 35,
    name: '浅绿刺绣旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '浅绿色刺绣面料，园林背景，清新雅致...',
    desc: '浅绿色刺绣面料，园林背景，清新雅致',
    detailDesc: '款式：浅绿刺绣旗袍\n类别：旗袍\n描述：浅绿色刺绣面料，园林背景，清新雅致\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(35),
    images: [clothingImage(35)],
    price: '¥1494',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 36,
    name: '红色刺绣旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '红色刺绣面料，喜庆吉祥...',
    desc: '红色刺绣面料，喜庆吉祥',
    detailDesc: '款式：红色刺绣旗袍\n类别：旗袍\n描述：红色刺绣面料，喜庆吉祥\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(36),
    images: [clothingImage(36)],
    price: '¥1531',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 37,
    name: '蓝色格子旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '蓝色格子面料，复古文艺...',
    desc: '蓝色格子面料，复古文艺',
    detailDesc: '款式：蓝色格子旗袍\n类别：旗袍\n描述：蓝色格子面料，复古文艺\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(37),
    images: [clothingImage(37)],
    price: '¥1568',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 38,
    name: '黄色条纹旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '黄色条纹面料，明快活泼...',
    desc: '黄色条纹面料，明快活泼',
    detailDesc: '款式：黄色条纹旗袍\n类别：旗袍\n描述：黄色条纹面料，明快活泼\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(38),
    images: [clothingImage(38)],
    price: '¥1605',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 39,
    name: '粉色蕾丝旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '粉色蕾丝面料，甜美优雅...',
    desc: '粉色蕾丝面料，甜美优雅',
    detailDesc: '款式：粉色蕾丝旗袍\n类别：旗袍\n描述：粉色蕾丝面料，甜美优雅\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(39),
    images: [clothingImage(39)],
    price: '¥1642',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 40,
    name: '米白刺绣旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '米白色刺绣面料，楼梯背景，温婉知性...',
    desc: '米白色刺绣面料，楼梯背景，温婉知性',
    detailDesc: '款式：米白刺绣旗袍\n类别：旗袍\n描述：米白色刺绣面料，楼梯背景，温婉知性\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(40),
    images: [clothingImage(40)],
    price: '¥1679',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 41,
    name: '黑色蕾丝旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '黑色蕾丝面料，神秘性感...',
    desc: '黑色蕾丝面料，神秘性感',
    detailDesc: '款式：黑色蕾丝旗袍\n类别：旗袍\n描述：黑色蕾丝面料，神秘性感\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(41),
    images: [clothingImage(41)],
    price: '¥1716',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 42,
    name: '绿色真丝旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '绿色真丝面料，清新自然...',
    desc: '绿色真丝面料，清新自然',
    detailDesc: '款式：绿色真丝旗袍\n类别：旗袍\n描述：绿色真丝面料，清新自然\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(42),
    images: [clothingImage(42)],
    price: '¥1753',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 43,
    name: '金色刺绣旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '金色刺绣面料，华贵大气...',
    desc: '金色刺绣面料，华贵大气',
    detailDesc: '款式：金色刺绣旗袍\n类别：旗袍\n描述：金色刺绣面料，华贵大气\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(43),
    images: [clothingImage(43)],
    price: '¥1790',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 44,
    name: '紫色丝绒旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '紫色丝绒面料，高贵典雅...',
    desc: '紫色丝绒面料，高贵典雅',
    detailDesc: '款式：紫色丝绒旗袍\n类别：旗袍\n描述：紫色丝绒面料，高贵典雅\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(44),
    images: [clothingImage(44)],
    price: '¥1827',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 45,
    name: '米色印花旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '米色印花面料，手持白花，温柔雅致...',
    desc: '米色印花面料，手持白花，温柔雅致',
    detailDesc: '款式：米色印花旗袍\n类别：旗袍\n描述：米色印花面料，手持白花，温柔雅致\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(45),
    images: [clothingImage(45)],
    price: '¥1864',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 46,
    name: '红色丝绒旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '红色丝绒面料，喜庆热烈...',
    desc: '红色丝绒面料，喜庆热烈',
    detailDesc: '款式：红色丝绒旗袍\n类别：旗袍\n描述：红色丝绒面料，喜庆热烈\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(46),
    images: [clothingImage(46)],
    price: '¥1901',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 47,
    name: '黄色短款旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '黄色短款旗袍，珍珠手提包，明媚动人...',
    desc: '黄色短款旗袍，珍珠手提包，明媚动人',
    detailDesc: '款式：黄色短款旗袍\n类别：旗袍\n描述：黄色短款旗袍，珍珠手提包，明媚动人\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(47),
    images: [clothingImage(47)],
    price: '¥1938',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
  {
    id: 48,
    name: '黑底红花旗袍',
    category: 'qipao',
    categoryName: '旗袍',
    subtitle: '黑色底红色花卉印花，古典园林背景，雍容华...',
    desc: '黑色底红色花卉印花，古典园林背景，雍容华贵',
    detailDesc: '款式：黑底红花旗袍\n类别：旗袍\n描述：黑色底红色花卉印花，古典园林背景，雍容华贵\n适合场合：日常穿着、拍照写真、节日聚会',
    image: clothingImage(48),
    images: [clothingImage(48)],
    price: '¥1975',
    tags: ['旗袍', '传统', '优雅'],
    liked: false
  },
]

module.exports = {
  categories,
  banners,
  clothingList,
  getByCategory(categoryId) {
    if (categoryId === 'all') return clothingList
    return clothingList.filter(item => item.category === categoryId)
  },
  getById(id) {
    return clothingList.find(item => item.id === parseInt(id))
  }
}